# Generated by Django 4.2.11 on 2024-04-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="date_joined",
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="refer_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
